# Generated by Django 4.2.6 on 2023-11-20 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='measurements', serialize=False, to='measurement.sensor'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Температура'),
        ),
    ]
